                          name: smoke-test
                          on:
                            workflow_dispatch:      # run manually from the Actions tab

                          jobs:
                            build-run:
                              runs-on: ubuntu-latest

                              steps:
                                # 1. Check out code
                                - uses: actions/checkout@v4

                                # 2. Build Docker image
                                - name: Build image
                                  run: docker build -t onedayahead:test .

                                # 3. Run container (NO --rm, so we can read logs later)
                                - name: Start container
                                  run: |
                                    docker run -d --name oda \
                                      -p 3000:3000 \
                                      -e PORT=3000 \
                                      -e NODE_ENV=production \
                                      -e SESSION_SECRET=dummy \
                                      -e DATABASE_URL=dummy \
                                      -e OPENAI_API_KEY=dummy \
                                      -e ANTHROPIC_API_KEY=dummy \
                                      onedayahead:test

                                # 4. Poll the health route (30-s timeout)
                                - name: Wait & curl
                                  run: |
                                    for i in {1..10}; do
                                      sleep 3
                                      if curl -fs http://localhost:3000/lti/health ; then
                                        echo "App is up"
                                        exit 0
                                      fi
                                    done
                                    echo "App never became ready" && exit 1

                                # 5. Always show container logs if we failed
                                - name: Show container logs if curl fails
                                  if: failure()
                                  run: docker logs oda || true