                  name: smoke-test
                  on:
                    workflow_dispatch:      # run manually from the Actions tab

                  jobs:
                    build-run:
                      runs-on: ubuntu-latest

                      steps:
                        # 1.  Checkout repo
                        - uses: actions/checkout@v4

                        # 2.  Build Docker image from the Dockerfile in the repo
                        - name: Build image
                          run: docker build -t onedayahead:test .

                        # 3. Start container with stubbed env-vars, expose port 3000
                        - name: Start container
                          run: |
                            docker run -d --rm --name oda \
                              -p 3000:3000 \
                              -e PORT=3000 \
                              -e NODE_ENV=production \
                              -e SESSION_SECRET=dummy \
                              -e DATABASE_URL=dummy \
                              onedayahead:test

                        # 4. Poll /lti/health (up to 30 s) to be sure the server is listening
                        - name: Wait & curl
                          run: |
                            for i in {1..10}; do
                              sleep 3
                              if curl -fs http://localhost:3000/lti/health ; then
                                echo "App is up"
                                exit 0
                              fi
                            done
                            echo "App never became ready" && exit 1

                        # 5.  If curl fails, show container logs so we can diagnose
                        - name: Show container logs if curl fails
                          if: failure()
                          run: docker logs oda || true