                                  name: smoke-test
                                  on:
                                    workflow_dispatch:      # run manually from the Actions tab

                                  jobs:
                                    build-run:
                                      runs-on: ubuntu-latest

                                      steps:
                                        # 1. Check out repo
                                        - uses: actions/checkout@v4

                                        # 2. Build Docker image from Dockerfile
                                        - name: Build image
                                          run: docker build -t onedayahead:test .

                                        # 3. Run container (keep it running so we can read logs)
                                        - name: Start container
                                          run: |
                                            docker run -d --name oda \
                                              -p 3000:3000 \
                                              -e PORT=3000 \
                                              -e NODE_ENV=production \
                                              -e SESSION_SECRET=dummy \
                                              -e DATABASE_URL=postgres://user:pass@localhost:5432/testdb \
                                              -e SKIP_DB_MIGRATIONS=true \
                                              onedayahead:test

                                        # 4. Poll /lti/health (up to 30 s) until server responds
                                        - name: Wait & curl
                                          run: |
                                            for i in {1..10}; do
                                              sleep 3
                                              if curl -fs http://localhost:3000/lti/health ; then
                                                echo "App is up"
                                                exit 0
                                              fi
                                            done
                                            echo "App never became ready" && exit 1

                                        # 5. If it still fails, show container logs for diagnosis
                                        - name: Show container logs if curl fails
                                          if: failure()
                                          run: docker logs oda || true